version: "3.9"

networks:
  default:
    external: true
    name: roboshop

services:
  mongodb:
    image: mongo:4.4

  catalogue:
    image: catalogue:1
    depends_on:
      - mongodb

  frontend:
    image: frontend:1
    ports:
      - "80:80"
    depends_on:
      - catalogue

  redis:
    image: redis:6-alpine

  user:
    image: user:1
    depends_on:
      - redis
      - mongodb

  cart:
    image: cart:1
    depends_on:
      - redis
      - catalogue
