networks:
  default:
    external: true
    name: roboshop

services:
  # MongoDB service
  mongodb:
    image: mongo:1         # official MongoDB image
  

  # Catalogue service
  catalogue:
    image: catalogue:1         # your custom image (must exist locally)
    depends_on:
      - mongodb

  # Frontend service
  frontend:
    image: frontend:1          # your custom image (must exist locally)
    ports:
      - "80:80"
    depends_on:
      - catalogue

  # Redis service
  redis:
    image: redis:1     # official Redis image


  # User service
  user:
    image: user:1              # your custom image (must exist locally)
    depends_on:
      - redis
      - mongodb

  # Cart service
  cart:
    image: cart:1              # your custom image (must exist locally)
    depends_on:
      - redis
      - catalogue
