networks:
  default:
    driver: bridge
    name: roboshop
    external: true #I created network already using docker network create roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq: # docker volume create rabbitmq
services:
  mongodb:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest mongodb:1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest catalogue:1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest user:1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest cart:1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest mysql:1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest shipping:1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest payment:1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: 872515251136.dkr.ecr.us-east-1.amazonaws.com/rajesh:latest frontend:1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
      
