networks:
  default:
    external: true
    name: roboshop

services:
  # Equivalent to: docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    image: mongodb:1

  # Equivalent to: docker run -d --name catalogue --network=roboshop catalogue:1
  catalogue:
    image: catalogue:1
    depends_on:
    - mongod

  frontend:
    image: frontend:1
    ports:
    - "80:80"
    depends_on:
    - catalogue
      # - user
      # - cart
      # - shipping
      # - payment
